### ISSUE TITLE
MV-Geschäftsordung: Keine Beschlüsse unter Verschiedenes

### ISSUE THREAD

**Issue by gonium** [C3MA/satzung#7]
Paragraph 4, Unterpunkt 6, 2. Satz: "sollen" durch "dürfen" ersetzen, es dürfen keine Beschlüsse unter "Verschiedenes" gefasst werden.

**Comment by tobima** [comment]
Ich bin dafür da dieser stelle das "sollen" durch "können" zu ersetzten. 
Ein entsprechender Antrag wird zur nächsten MV gestellt.

**Comment by tobima** [comment]
#13

**Comment by tobima** [comment]
Mit dem Merge von #13 hat sich dieses Thema erledigt. Ich mache hier mal zu.
